server:
  port: 8081

spring:
  application:
    name: user-service

 

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.springframework: TRACE
#    org.springframework.beans.factory: TRACE
#    org.springframework.boot: TRACE
#    com.baomidou.mybatisplus: TRACE
    # 根据需要进一步设置其他包的日志级别


