server:
  port: 8081

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/share?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver